/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
          "on-surface": "#e2e2e8",
          "surface": "#111317",
          "surface-variant": "#333539",
          "on-error": "#690005",
          "inverse-on-surface": "#2f3035",
          "on-error-container": "#ffdad6",
          "secondary-fixed-dim": "#d0bcff",
          "primary": "#b8c3ff",
          "on-surface-variant": "#c4c5d9",
          "tertiary-container": "#00797e",
          "surface-bright": "#37393e",
          "on-secondary-fixed": "#23005c",
          "surface-container-high": "#282a2e",
          "on-primary-container": "#efefff",
          "tertiary-fixed": "#63f7ff",
          "surface-container": "#1e2024",
          "on-secondary-container": "#c4abff",
          "surface-container-lowest": "#0c0e12",
          "on-tertiary": "#003739",
          "on-primary-fixed": "#001356",
          "inverse-surface": "#e2e2e8",
          "primary-fixed-dim": "#b8c3ff",
          "primary-fixed": "#dde1ff",
          "surface-container-highest": "#333539",
          "tertiary-fixed-dim": "#00dce5",
          "on-tertiary-container": "#bbfbff",
          "outline-variant": "#434656",
          "on-background": "#e2e2e8",
          "on-secondary-fixed-variant": "#5516be",
          "surface-dim": "#111317",
          "secondary-container": "#571bc1",
          "surface-tint": "#b8c3ff",
          "secondary-fixed": "#e9ddff",
          "primary-container": "#2e5bff",
          "on-primary-fixed-variant": "#0035be",
          "on-tertiary-fixed": "#002021",
          "secondary": "#d0bcff",
          "on-secondary": "#3c0091",
          "tertiary": "#00dce5",
          "error": "#ffb4ab",
          "inverse-primary": "#124af0",
          "on-primary": "#002388",
          "on-tertiary-fixed-variant": "#004f53",
          "background": "#111317",
          "error-container": "#93000a",
          "surface-container-low": "#1a1c20",
          "outline": "#8e90a2"
      },
      borderRadius: {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      spacing: {
          "xs": "4px",
          "unit": "4px",
          "gutter": "16px",
          "xl": "80px",
          "base": "8px",
          "sm": "12px",
          "md": "24px",
          "margin": "40px",
          "lg": "48px",
          "control-bar-height": "72px",
          "edge-margin-tablet": "32px",
          "edge-margin-mobile": "16px"
      },
      fontFamily: {
          "body-md": ["Inter", "sans-serif"],
          "body-lg": ["Inter", "sans-serif"],
          "label-caps": ["Inter", "sans-serif"],
          "headline-md": ["Inter", "sans-serif"],
          "headline-lg": ["Inter", "sans-serif"],
          "display-xl": ["Inter", "sans-serif"],
          "prompter-standard": ["Inter", "sans-serif"],
          "prompter-display": ["Inter", "sans-serif"]
      },
      fontSize: {
          "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
          "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
          "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
          "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
          "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "0.01em", "fontWeight": "600" }],
          "display-xl": ["72px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
          "prompter-standard": ["32px", { "lineHeight": "1.4", "letterSpacing": "-0.01em", "fontWeight": "600" }],
          "prompter-display": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
