import React, { createContext, useContext, useState, useEffect } from 'react';

const legacyTranslations = {
  en: {
    appName: 'ScriptFlow',
    myScripts: 'My Scripts',
    createNew: 'Create New Script',
    importTxt: 'Import .TXT File',
    scripts: 'Scripts',
    editor: 'Editor',
    record: 'Record',
    settings: 'Settings',
    filter: 'Filter',
    favorites: 'Favorites',
    recentRecordings: 'Recent Recordings',
    cloudSync: 'Cloud Sync',
    helpSupport: 'Help & Support',
    editScript: 'Edit Script',
    startRecording: 'Start Recording',
    titlePlaceholder: 'Script Title',
    contentPlaceholder: 'Start typing your script here...',
    wordCount: 'words',
    start: 'Start',
    stop: 'Stop',
    startRec: 'Start Recording',
    size: 'Size',
    viewMode: 'Layout',
    prompterOnly: 'Prompter Only',
    filters: 'Filters',
    layouts: 'Layouts',
    textSize: 'Text Size',
    close: 'Close',
    reviewRecording: 'Review Recording',
    discardRetake: 'Discard & Retake',
    saveVideo: 'Save Video',
    cameraFilters: 'Camera Filters',
    language: 'Language',
    untitledScript: 'Untitled Script',
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    scriptsCount: 'scripts · you are ready',
    noScripts: 'No scripts yet',
    createBelow: 'Create a new script below',
    newScript: 'New Script',
    importText: 'Import',
    deleteScriptMsg: 'Delete script?',
    cannotUndo: 'This action cannot be undone.',
    cancel: 'Cancel',
    delete: 'Delete',
    myVideos: 'My Recordings',
    saved: 'Saved!',
    save: 'Save',
    menu: 'Menu',
    ready: 'READY',
    recording: 'RECORD',
    reading: 'READING',
    read: 'READ',
    flipCamera: 'Flip Camera',
    getReady: 'Get Ready...',
    videoSettings: 'Video Settings',
    textColor: 'Text Color',
    quality: 'Quality',
    webmNote: '✓ All videos are saved in WebM format for device compatibility.',
    eyeContact: 'Eye Contact Mode (Width)',
    countdown: 'Countdown',
    saving: 'Saving...',
    saveSuccess: 'Saved to your device!',
    saveError: 'Error saving recording!',
    saveToDevice: 'Save to Device',
    deleteAndRetake: 'Delete & Retake',
    newRecording: 'New Recording',
    sortNewest: 'Sort: Newest First',
    noVideos: 'No videos yet',
    recordFirst: 'Record your first video from the record screen.',
    videoLoading: 'Loading video...',
    switchToLang: 'Türkçe\'ye Geç',
    deleteVideoMsg: 'Are you sure you want to delete this video?',
    deleteError: 'Error deleting: ',
    shareError: 'Share error: ',
    shareVideoTitle: 'Share Video',
    recordedWith: 'Recorded with ScriptFlow',
    noVideosDesc: 'No saved videos found.',
    recordingPrefix: 'Recording ',
    playVideo: 'Play Video',
    share: 'Share',
    tutorial: 'How to Use',
    tutorialStep1Title: 'Add a Script',
    tutorialStep1Desc: 'On the My Scripts screen, tap "New Script" to write your text or import an existing file from your device.',
    tutorialStep2Title: 'Edit',
    tutorialStep2Desc: 'While editing, use the A- and A+ buttons at the bottom to adjust the text size to suit your eyes.',
    tutorialStep3Title: 'Record & Prompter',
    tutorialStep3Desc: 'Go to the Record screen. Select front/back camera from the camera icon. Adjust scroll speed with the +/- buttons on the right and start recording.',
    tutorialStep4Title: 'Share',
    tutorialStep4Desc: 'When recording finishes, tap "Save to Device" then share instantly to social media or friends.',
    tutorialStep5Title: 'Bluetooth Remote',
    tutorialStep5Desc: 'Connect any Bluetooth presentation clicker or remote to control the prompter. Use Space/Play to start, and Up/Down arrows to adjust speed remotely.',
    tutorialBack: 'Back',
    tutorialNext: 'Next',
    tutorialFinish: 'Start',
    splashTagline: 'Smart prompter for professional shots',
    splashLoading: 'Loading...',
    langSwitch: 'Switch to Turkish',
    videoRecord: 'Record Video',
    audioRecord: 'Record Audio',
    loading: 'Loading...',
    scriptsReady: 'scripts ready',
    wordCountUpper: 'WORDS',
    bgColor: 'Background Color',
    camSettings: 'Camera Settings (Pro)',
    fps: 'Frame Rate (FPS)',
    zoom: 'Zoom',
    smartVoice: 'Smart Voice',
    camBottom: 'Half Screen',
    fullScreen: 'Full Screen',
    cleanText: 'Clean Text',
    color_none: 'Clear',
    color_black: 'Black',
    color_navy: 'Navy',
    color_dark: 'Dark Gray',
    color_green: 'Green',
    color_red: 'Red',
    color_purple: 'Purple',
    color_white: 'White',
    filter_clean: 'Clean',
    filter_warm: 'Warm',
    filter_cool: 'Cool',
    filter_cinema: 'Cinema',
    filter_portrait: 'Portrait',
    filter_studio: 'Studio',
    filter_bw: 'B&W',
    filter_vivid: 'Vivid',
    filter_beauty: 'Beauty', filter_retro: 'Retro', filter_dramatic: 'Dramatic', filter_golden: 'Golden Hour', filter_broadcast: 'Broadcast', filter_matte: 'Matte', filter_night: 'Night',
    width_wide: 'Wide',
    width_medium: 'Medium',
    width_narrow: 'Narrow',
  },
  tr: {
    appName: 'ScriptFlow',
    myScripts: 'Metinlerim',
    createNew: 'Yeni Metin Oluştur',
    importTxt: '.TXT Dosyası İçe Aktar',
    scripts: 'Metinler',
    editor: 'Düzenle',
    record: 'Kayıt',
    settings: 'Ayarlar',
    filter: 'Filtre',
    favorites: 'Favoriler',
    recentRecordings: 'Son Kayıtlar',
    cloudSync: 'Bulut Senkron',
    helpSupport: 'Yardım & Destek',
    editScript: 'Metni Düzenle',
    startRecording: 'Kaydı Başlat',
    titlePlaceholder: 'Metin Başlığı',
    contentPlaceholder: 'Metninizi buraya yazmaya başlayın...',
    wordCount: 'kelime',
    start: 'Başlat',
    stop: 'Durdur',
    startRec: 'Kayda Başla',
    size: 'Boyut',
    viewMode: 'Görünüm',
    prompterOnly: 'Sadece Metin',
    filters: 'Filtreler',
    layouts: 'Düzen',
    textSize: 'Yazı Boyutu',
    close: 'Kapat',
    reviewRecording: 'Kaydı İncele',
    discardRetake: 'Sil & Tekrar Çek',
    saveVideo: 'Videoyu Kaydet',
    cameraFilters: 'Kamera Filtreleri',
    language: 'Dil',
    untitledScript: 'İsimsiz Metin',
    goodMorning: 'Günaydın',
    goodAfternoon: 'İyi günler',
    goodEvening: 'İyi akşamlar',
    scriptsCount: 'metin · hepsine hazırsın',
    noScripts: 'Henüz metin yok',
    createBelow: 'Aşağıdan yeni bir metin oluştur',
    newScript: 'Yeni Metin',
    importText: 'İçe Aktar',
    deleteScriptMsg: 'Metni sil?',
    cannotUndo: 'Bu işlem geri alınamaz.',
    cancel: 'İptal',
    delete: 'Sil',
    myVideos: 'Kayıtlarım',
    saved: 'Kaydedildi!',
    save: 'Kaydet',
    menu: 'Menü',
    ready: 'HAZIR',
    recording: 'KAYIT',
    reading: 'OKUNUYOR',
    read: 'OKU',
    flipCamera: 'Kamerayı Çevir',
    getReady: 'Hazırlan...',
    videoSettings: 'Video Ayarları',
    textColor: 'Yazı Rengi',
    quality: 'Kalite',
    webmNote: '✓ Tüm videolar cihaz uyumluluğu için WebM formatında kaydedilir.',
    eyeContact: 'Göz Teması Modu (Genişlik)',
    countdown: 'Geri Sayım',
    saving: 'Kaydediliyor...',
    saveSuccess: 'Videolarım klasörüne eklendi!',
    saveError: 'Kayıt hatası oluştu!',
    saveToDevice: 'Cihaza Kaydet',
    deleteAndRetake: 'Sil ve Yeniden Çek',
    newRecording: 'Yeni Kayda Geç',
    sortNewest: 'Sırala: Yeniden Eskiye',
    noVideos: 'Henüz video yok',
    recordFirst: 'Kayıt ekranından ilk videonuzu çekin.',
    videoLoading: 'Video yükleniyor...',
    switchToLang: 'Switch to English',
    deleteVideoMsg: 'Bu videoyu silmek istediğinize emin misiniz?',
    deleteError: 'Silinirken hata oluştu: ',
    shareError: 'Paylaşım hatası: ',
    shareVideoTitle: 'Videoyu Paylaş',
    recordedWith: 'ScriptFlow ile çekildi',
    noVideosDesc: 'Henüz kayıtlı video bulunmuyor.',
    recordingPrefix: 'Kayıt ',
    playVideo: 'Videoyu oynat',
    share: 'Paylaş',
    tutorial: 'Nasıl Kullanılır?',
    tutorialStep1Title: 'Metin Ekleme',
    tutorialStep1Desc: 'Metinlerim ekranında "Yeni Metin" butonuna basarak okuyacağınız metni yazın veya var olan bir metni cihaza kaydedip uygulamaya aktarın.',
    tutorialStep2Title: 'Düzenleme',
    tutorialStep2Desc: 'Metnini düzenlerken alttaki A- A+ butonlarını kullanarak metnin okuma boyutunu kendi gözünüze uygun hale getirin.',
    tutorialStep3Title: 'Kayıt ve Prompter',
    tutorialStep3Desc: 'Kayıt ekranına geçin. Kamera ikonundan ön/arka kamerayı seçin. Metin akış hızını sağdaki +/- butonlarından ayarlayarak kayda başlayın.',
    tutorialStep4Title: 'Paylaşım',
    tutorialStep4Desc: 'Kayıt bittiğinde "Cihaza Kaydet" diyerek galeriye atabilir, ardından anında sosyal medyada arkadaşlarınızla paylaşabilirsiniz.',
    tutorialStep5Title: 'Bluetooth Kumanda',
    tutorialStep5Desc: 'Telefona bağladığınız herhangi bir Bluetooth sunum kumandası veya deklanşör ile metni uzaktan kontrol edebilirsiniz (Başlat/Durdur ve Hız Ayarı).',
    tutorialBack: 'Geri',
    tutorialNext: 'İleri',
    tutorialFinish: 'Başla',
    splashTagline: 'Profesyonel çekimler için akıllı prompter',
    splashLoading: 'Hazırlanıyor...',
    langSwitch: 'Switch to English',
    videoRecord: 'Video Kaydı Yap',
    audioRecord: 'Ses Kaydı Yap',
    loading: 'Yükleniyor...',
    scriptsReady: 'metin hazır',
    wordCountUpper: 'KELİME',
    bgColor: 'Arka Plan Rengi',
    camSettings: 'Kamera Ayarları (Pro)',
    fps: 'Kare Hızı (FPS)',
    zoom: 'Yakınlaştırma',
    smartVoice: 'Akıllı Ses',
    camBottom: 'Yarım Ekran',
    fullScreen: 'Tam Ekran',
    cleanText: 'Temiz',
    color_none: 'Saydam',
    color_black: 'Siyah',
    color_navy: 'Lacivert',
    color_dark: 'Koyu Gri',
    color_green: 'Yeşil',
    color_red: 'Kırmızı',
    color_purple: 'Mor',
    color_white: 'Beyaz',
    filter_clean: 'Temiz',
    filter_warm: 'Sıcak',
    filter_cool: 'Soğuk',
    filter_cinema: 'Sinema',
    filter_portrait: 'Portre',
    filter_studio: 'Stüdyo',
    filter_bw: 'S/B',
    filter_vivid: 'Canlı',
    filter_beauty: 'Pürüzsüz', filter_retro: 'Retro', filter_dramatic: 'Dramatik', filter_golden: 'Altın Saat', filter_broadcast: 'Yayıncı', filter_matte: 'Matte', filter_night: 'Gece',
    width_wide: 'Geniş',
    width_medium: 'Orta',
    width_narrow: 'Dar',
  },
  de: {
    appName: 'ScriptFlow',
    myScripts: 'Meine Skripte',
    createNew: 'Neues Skript erstellen',
    importTxt: '.TXT-Datei importieren',
    scripts: 'Skripte',
    editor: 'Editor',
    record: 'Aufnehmen',
    settings: 'Einstellungen',
    filter: 'Filter',
    favorites: 'Favoriten',
    recentRecordings: 'Letzte Aufnahmen',
    cloudSync: 'Cloud-Sync',
    helpSupport: 'Hilfe & Support',
    editScript: 'Skript bearbeiten',
    startRecording: 'Aufnahme starten',
    titlePlaceholder: 'Skripttitel',
    contentPlaceholder: 'Tippe hier dein Skript...',
    wordCount: 'Wörter',
    start: 'Start',
    stop: 'Stopp',
    startRec: 'Aufnahme starten',
    size: 'Größe',
    viewMode: 'Layout',
    prompterOnly: 'Nur Text',
    filters: 'Filter',
    layouts: 'Layouts',
    textSize: 'Textgröße',
    close: 'Schließen',
    reviewRecording: 'Aufnahme prüfen',
    discardRetake: 'Verwerfen & neu aufnehmen',
    saveVideo: 'Video speichern',
    cameraFilters: 'Kamerafilter',
    language: 'Sprache',
    untitledScript: 'Unbenanntes Skript',
    goodMorning: 'Guten Morgen',
    goodAfternoon: 'Guten Tag',
    goodEvening: 'Guten Abend',
    scriptsCount: 'Skripte · bereit',
    noScripts: 'Noch keine Skripte',
    createBelow: 'Erstelle unten ein neues Skript',
    newScript: 'Neues Skript',
    importText: 'Importieren',
    deleteScriptMsg: 'Skript löschen?',
    cannotUndo: 'Diese Aktion kann nicht rückgängig gemacht werden.',
    cancel: 'Abbrechen',
    delete: 'Löschen',
    myVideos: 'Meine Aufnahmen',
    saved: 'Gespeichert!',
    save: 'Speichern',
    menu: 'Menü',
    ready: 'BEREIT',
    recording: 'AUFNAHME',
    reading: 'LESEN',
    read: 'LESEN',
    flipCamera: 'Kamera wechseln',
    getReady: 'Bereit machen...',
    videoSettings: 'Videoeinstellungen',
    textColor: 'Textfarbe',
    quality: 'Qualität',
    webmNote: '✓ Alle Videos werden im WebM-Format gespeichert.',
    eyeContact: 'Augenkontakt-Modus (Breite)',
    countdown: 'Countdown',
    saving: 'Wird gespeichert...',
    saveSuccess: 'Auf dem Gerät gespeichert!',
    saveError: 'Fehler beim Speichern!',
    saveToDevice: 'Auf Gerät speichern',
    deleteAndRetake: 'Löschen & neu aufnehmen',
    newRecording: 'Neue Aufnahme',
    sortNewest: 'Sortieren: Neueste zuerst',
    noVideos: 'Noch keine Videos',
    recordFirst: 'Nimm dein erstes Video vom Aufnahmebildschirm auf.',
    videoLoading: 'Video wird geladen...',
    switchToLang: 'Türkçe\'ye Geç',
    deleteVideoMsg: 'Dieses Video wirklich löschen?',
    deleteError: 'Fehler beim Löschen: ',
    shareError: 'Fehler beim Teilen: ',
    shareVideoTitle: 'Video teilen',
    recordedWith: 'Aufgenommen mit ScriptFlow',
    noVideosDesc: 'Keine gespeicherten Videos gefunden.',
    recordingPrefix: 'Aufnahme ',
    playVideo: 'Video abspielen',
    share: 'Teilen',
    tutorial: 'Anleitung',
    tutorialStep1Title: 'Skript hinzufügen',
    tutorialStep1Desc: 'Tippe auf "Neues Skript" und schreibe deinen Text oder importiere eine Datei vom Gerät.',
    tutorialStep2Title: 'Bearbeiten',
    tutorialStep2Desc: 'Verwende die A- und A+ Schaltflächen, um die Textgröße anzupassen.',
    tutorialStep3Title: 'Aufnehmen & Prompter',
    tutorialStep3Desc: 'Gehe zum Aufnahmebildschirm. Wähle die Kamera und stelle die Scrollgeschwindigkeit ein.',
    tutorialStep4Title: 'Teilen',
    tutorialStep4Desc: 'Speichere nach der Aufnahme das Video und teile es direkt in sozialen Medien.',
    tutorialStep5Title: 'Bluetooth-Fernbedienung',
    tutorialStep5Desc: 'Verbinde einen Bluetooth-Presenter, um den Prompter fernzusteuern.',
    tutorialBack: 'Zurück',
    tutorialNext: 'Weiter',
    tutorialFinish: 'Start',
    splashTagline: 'Intelligenter Prompter für professionelle Aufnahmen',
    splashLoading: 'Wird geladen...',
    langSwitch: 'Türkçe\'ye Geç',
    videoRecord: 'Video aufnehmen',
    audioRecord: 'Audio aufnehmen',
    loading: 'Wird geladen...',
    scriptsReady: 'Skripte bereit',
    wordCountUpper: 'WÖRTER',
    bgColor: 'Hintergrundfarbe',
    camSettings: 'Kameraeinstellungen (Pro)',
    fps: 'Bildrate (FPS)',
    zoom: 'Zoom',
    smartVoice: 'Intelligente Stimme',
    camBottom: 'Halber Bildschirm',
    fullScreen: 'Vollbild',
    cleanText: 'Reiner Text',
    color_none: 'Transparent',
    color_black: 'Schwarz',
    color_navy: 'Marine',
    color_dark: 'Dunkelgrau',
    color_green: 'Grün',
    color_red: 'Rot',
    color_purple: 'Lila',
    color_white: 'Weiß',
    filter_clean: 'Sauber',
    filter_warm: 'Warm',
    filter_cool: 'Kühl',
    filter_cinema: 'Kino',
    filter_portrait: 'Porträt',
    filter_studio: 'Studio',
    filter_bw: 'S/W',
    filter_vivid: 'Lebendig',
    filter_beauty: 'Beauty', filter_retro: 'Retro', filter_dramatic: 'Dramatisch', filter_golden: 'Goldene Stunde', filter_broadcast: 'Broadcast', filter_matte: 'Matt', filter_night: 'Nacht',
    width_wide: 'Breit',
    width_medium: 'Mittel',
    width_narrow: 'Schmal',
  }
};

const enTranslations = legacyTranslations.en;
const trTranslations = legacyTranslations.tr;
const deTranslations = legacyTranslations.de;


// ── ESPAÑOL ───────────────────────────────────────────────────────────────
const esTranslations = {
  appName: 'ScriptFlow',
  myScripts: 'Mis Guiones',
  createNew: 'Crear nuevo guín',
  importTxt: 'Importar archivo .TXT',
  scripts: 'Guiones',
  editor: 'Editor',
  record: 'Grabar',
  settings: 'Ajustes',
  filter: 'Filtro',
  favorites: 'Favoritos',
  recentRecordings: 'Últimas grabaciones',
  cloudSync: 'Sincronización en la nube',
  helpSupport: 'Ayuda y soporte',
  editScript: 'Editar guín',
  startRecording: 'Iniciar grabación',
  titlePlaceholder: 'Título del guín',
  contentPlaceholder: 'Empieza a escribir tu guín...',
  wordCount: 'palabras',
  start: 'Iniciar',
  stop: 'Parar',
  startRec: 'Iniciar grabación',
  size: 'Tamaño',
  viewMode: 'Diseño',
  prompterOnly: 'Solo texto',
  filters: 'Filtros',
  layouts: 'Disposición',
  textSize: 'Tamaño de texto',
  close: 'Cerrar',
  reviewRecording: 'Revisar grabación',
  discardRetake: 'Descartar y repetir',
  saveVideo: 'Guardar vídeo',
  cameraFilters: 'Filtros de cámara',
  language: 'Idioma',
  untitledScript: 'Guín sin título',
  goodMorning: 'Buenos días',
  goodAfternoon: 'Buenas tardes',
  goodEvening: 'Buenas noches',
  scriptsCount: 'guiones · listo',
  noScripts: 'Aún no hay guiones',
  createBelow: 'Crea un nuevo guín abajo',
  newScript: 'Nuevo guín',
  importText: 'Importar',
  deleteScriptMsg: '¿Eliminar guín?',
  cannotUndo: 'Esta acción no se puede deshacer.',
  cancel: 'Cancelar',
  delete: 'Eliminar',
  myVideos: 'Mis grabaciones',
  saved: '¡Guardado!',
  save: 'Guardar',
  menu: 'Menú',
  ready: 'LISTO',
  recording: 'GRABANDO',
  reading: 'LEYENDO',
  read: 'LEER',
  flipCamera: 'Cambiar cámara',
  getReady: 'Prepárate...',
  videoSettings: 'Ajustes de vídeo',
  textColor: 'Color de texto',
  quality: 'Calidad',
  webmNote: '✓ Todos los vídeos se guardan en formato WebM.',
  eyeContact: 'Modo contacto visual (Ancho)',
  countdown: 'Cuenta atrás',
  saving: 'Guardando...',
  saveSuccess: '¡Guardado en tu dispositivo!',
  saveError: '¡Error al guardar!',
  saveToDevice: 'Guardar en dispositivo',
  deleteAndRetake: 'Eliminar y repetir',
  newRecording: 'Nueva grabación',
  sortNewest: 'Ordenar: Más reciente',
  noVideos: 'Aún no hay vídeos',
  recordFirst: 'Graba tu primer vídeo desde la pantalla de grabación.',
  videoLoading: 'Cargando vídeo...',
  switchToLang: 'Türkçe\'ye Geç',
  deleteVideoMsg: '¿Eliminar este vídeo?',
  deleteError: 'Error al eliminar: ',
  shareError: 'Error al compartir: ',
  shareVideoTitle: 'Compartir vídeo',
  recordedWith: 'Grabado con ScriptFlow',
  noVideosDesc: 'No se encontraron vídeos guardados.',
  recordingPrefix: 'Grabación ',
  playVideo: 'Reproducir vídeo',
  share: 'Compartir',
  tutorial: 'Cómo usar',
  tutorialStep1Title: 'Añadir un guín',
  tutorialStep1Desc: 'En la pantalla Mis Guiones, pulsa "Nuevo guín" para escribir tu texto o importar un archivo.',
  tutorialStep2Title: 'Editar',
  tutorialStep2Desc: 'Usa los botones A- y A+ para ajustar el tamaño del texto.',
  tutorialStep3Title: 'Grabar y Prompter',
  tutorialStep3Desc: 'Ve a la pantalla de grabación. Selecciona la cámara y ajusta la velocidad de desplazamiento.',
  tutorialStep4Title: 'Compartir',
  tutorialStep4Desc: 'Al terminar, guarda el vídeo y compártelo en redes sociales.',
  tutorialStep5Title: 'Control Bluetooth',
  tutorialStep5Desc: 'Conecta un presentador Bluetooth para controlar el prompter de forma remota.',
  tutorialBack: 'Atrás',
  tutorialNext: 'Siguiente',
  tutorialFinish: 'Comenzar',
  splashTagline: 'Prompter inteligente para grabaciones profesionales',
  splashLoading: 'Cargando...',
  langSwitch: 'Türkçe\'ye Geç',
  videoRecord: 'Grabar vídeo',
  audioRecord: 'Grabar audio',
  loading: 'Cargando...',
  scriptsReady: 'guiones listos',
  wordCountUpper: 'PALABRAS',
  bgColor: 'Color de fondo',
  camSettings: 'Ajustes de cámara (Pro)',
  fps: 'Velocidad de fotogramas (FPS)',
  zoom: 'Zoom',
  smartVoice: 'Voz inteligente',
  camBottom: 'Media Pantalla',
  fullScreen: 'Pantalla completa',
  cleanText: 'Texto Limpio',
  color_none: 'Transparente',
  color_black: 'Negro',
  color_navy: 'Azul marino',
  color_dark: 'Gris oscuro',
  color_green: 'Verde',
  color_red: 'Rojo',
  color_purple: 'Morado',
  color_white: 'Blanco',
  filter_clean: 'Limpio',
  filter_warm: 'Cálido',
  filter_cool: 'Frío',
  filter_cinema: 'Cine',
  filter_portrait: 'Retrato',
  filter_studio: 'Estudio',
  filter_bw: 'B/N',
  filter_vivid: 'Vivo',
  filter_beauty: 'Belleza', filter_retro: 'Retro', filter_dramatic: 'Dramático', filter_golden: 'Hora Dorada', filter_broadcast: 'Transmisión', filter_matte: 'Mate', filter_night: 'Noche',
  width_wide: 'Ancho',
  width_medium: 'Medio',
  width_narrow: 'Estrecho',
};

// ── FRANÇAIS ───────────────────────────────────────────────────────────────
const frTranslations = {
  appName: 'ScriptFlow',
  myScripts: 'Mes Scripts',
  createNew: 'Créer un nouveau script',
  importTxt: 'Importer un fichier .TXT',
  scripts: 'Scripts',
  editor: 'Éditeur',
  record: 'Enregistrer',
  settings: 'Paramètres',
  filter: 'Filtre',
  favorites: 'Favoris',
  recentRecordings: 'Enregistrements récents',
  cloudSync: 'Synchronisation cloud',
  helpSupport: 'Aide & Support',
  editScript: 'Modifier le script',
  startRecording: 'Démarrer l\'enregistrement',
  titlePlaceholder: 'Titre du script',
  contentPlaceholder: 'Commencez à écrire votre script...',
  wordCount: 'mots',
  start: 'Démarrer',
  stop: 'Arrêter',
  startRec: 'Démarrer l\'enregistrement',
  size: 'Taille',
  viewMode: 'Mise en page',
  prompterOnly: 'Texte uniquement',
  filters: 'Filtres',
  layouts: 'Dispositions',
  textSize: 'Taille du texte',
  close: 'Fermer',
  reviewRecording: 'Revoir l\'enregistrement',
  discardRetake: 'Supprimer & reprendre',
  saveVideo: 'Enregistrer la vidéo',
  cameraFilters: 'Filtres caméra',
  language: 'Langue',
  untitledScript: 'Script sans titre',
  goodMorning: 'Bonjour',
  goodAfternoon: 'Bon après-midi',
  goodEvening: 'Bonsoir',
  scriptsCount: 'scripts · prêts',
  noScripts: 'Aucun script pour l\'instant',
  createBelow: 'Créez un nouveau script ci-dessous',
  newScript: 'Nouveau script',
  importText: 'Importer',
  deleteScriptMsg: 'Supprimer le script ?',
  cannotUndo: 'Cette action est irréversible.',
  cancel: 'Annuler',
  delete: 'Supprimer',
  myVideos: 'Mes enregistrements',
  saved: 'Enregistré !',
  save: 'Enregistrer',
  menu: 'Menu',
  ready: 'PRÊT',
  recording: 'ENREGISTREMENT',
  reading: 'LECTURE',
  read: 'LIRE',
  flipCamera: 'Changer de caméra',
  getReady: 'Préparez-vous...',
  videoSettings: 'Paramètres vidéo',
  textColor: 'Couleur du texte',
  quality: 'Qualité',
  webmNote: '✓ Toutes les vidéos sont enregistrées au format WebM.',
  eyeContact: 'Mode contact visuel (Largeur)',
  countdown: 'Compte à rebours',
  saving: 'Enregistrement...',
  saveSuccess: 'Enregistré sur votre appareil !',
  saveError: 'Erreur lors de l\'enregistrement !',
  saveToDevice: 'Enregistrer sur l\'appareil',
  deleteAndRetake: 'Supprimer et reprendre',
  newRecording: 'Nouvel enregistrement',
  sortNewest: 'Trier : Plus récent',
  noVideos: 'Aucune vidéo pour l\'instant',
  recordFirst: 'Enregistrez votre première vidéo depuis l\'écran d\'enregistrement.',
  videoLoading: 'Chargement de la vidéo...',
  switchToLang: 'Türkçe\'ye Geç',
  deleteVideoMsg: 'Supprimer cette vidéo ?',
  deleteError: 'Erreur lors de la suppression : ',
  shareError: 'Erreur de partage : ',
  shareVideoTitle: 'Partager la vidéo',
  recordedWith: 'Enregistré avec ScriptFlow',
  noVideosDesc: 'Aucune vidéo enregistrée trouvée.',
  recordingPrefix: 'Enregistrement ',
  playVideo: 'Lire la vidéo',
  share: 'Partager',
  tutorial: 'Comment utiliser',
  tutorialStep1Title: 'Ajouter un script',
  tutorialStep1Desc: 'Sur l\'écran Mes Scripts, appuyez sur "Nouveau script" pour écrire ou importer un fichier.',
  tutorialStep2Title: 'Éditer',
  tutorialStep2Desc: 'Utilisez les boutons A- et A+ pour ajuster la taille du texte.',
  tutorialStep3Title: 'Enregistrer & Prompteur',
  tutorialStep3Desc: 'Allez à l\'écran d\'enregistrement, choisissez la caméra et réglez la vitesse de défilement.',
  tutorialStep4Title: 'Partager',
  tutorialStep4Desc: 'Après l\'enregistrement, sauvegardez la vidéo et partagez-la sur les réseaux sociaux.',
  tutorialStep5Title: 'Télécommande Bluetooth',
  tutorialStep5Desc: 'Connectez un présentateur Bluetooth pour contrôler le prompteur à distance.',
  tutorialBack: 'Retour',
  tutorialNext: 'Suivant',
  tutorialFinish: 'Commencer',
  splashTagline: 'Prompteur intelligent pour des prises de vue professionnelles',
  splashLoading: 'Chargement...',
  langSwitch: 'Türkçe\'ye Geç',
  videoRecord: 'Enregistrer une vidéo',
  audioRecord: 'Enregistrer l\'audio',
  loading: 'Chargement...',
  scriptsReady: 'scripts prêts',
  wordCountUpper: 'MOTS',
  bgColor: 'Couleur de fond',
  camSettings: 'Paramètres caméra (Pro)',
  fps: 'Fréquence d\'images (FPS)',
  zoom: 'Zoom',
  smartVoice: 'Voix intelligente',
  camBottom: 'Demi-Écran',
  fullScreen: 'Plein écran',
  cleanText: 'Texte Clair',
  color_none: 'Transparent',
  color_black: 'Noir',
  color_navy: 'Marine',
  color_dark: 'Gris foncé',
  color_green: 'Vert',
  color_red: 'Rouge',
  color_purple: 'Violet',
  color_white: 'Blanc',
  filter_clean: 'Net',
  filter_warm: 'Chaud',
  filter_cool: 'Froid',
  filter_cinema: 'Cinéma',
  filter_portrait: 'Portrait',
  filter_studio: 'Studio',
  filter_bw: 'N/B',
  filter_vivid: 'Vif',
  filter_beauty: 'Beauté', filter_retro: 'Rétro', filter_dramatic: 'Dramatique', filter_golden: 'Heure Dorée', filter_broadcast: 'Diffusion', filter_matte: 'Mat', filter_night: 'Nuit',
  width_wide: 'Large',
  width_medium: 'Moyen',
  width_narrow: 'Étroit',
};

// ── РУССКИЙ ───────────────────────────────────────────────────────────────
const ruTranslations = {
  appName: 'ScriptFlow',
  myScripts: 'Мои сценарии',
  createNew: 'Создать новый сценарий',
  importTxt: 'Импортировать .TXT файл',
  scripts: 'Сценарии',
  editor: 'Редактор',
  record: 'Запись',
  settings: 'Настройки',
  filter: 'Фильтр',
  favorites: 'Избранное',
  recentRecordings: 'Последние записи',
  cloudSync: 'Облачная синхронизация',
  helpSupport: 'Помощь и поддержка',
  editScript: 'Редактировать сценарий',
  startRecording: 'Начать запись',
  titlePlaceholder: 'Название сценария',
  contentPlaceholder: 'Начните вводить текст...',
  wordCount: 'слов',
  start: 'Старт',
  stop: 'Стоп',
  startRec: 'Начать запись',
  size: 'Размер',
  viewMode: 'Макет',
  prompterOnly: 'Только текст',
  filters: 'Фильтры',
  layouts: 'Макеты',
  textSize: 'Размер текста',
  close: 'Закрыть',
  reviewRecording: 'Просмотр записи',
  discardRetake: 'Удалить и переснять',
  saveVideo: 'Сохранить видео',
  cameraFilters: 'Фильтры камеры',
  language: 'Язык',
  untitledScript: 'Без названия',
  goodMorning: 'Доброе утро',
  goodAfternoon: 'Добрый день',
  goodEvening: 'Добрый вечер',
  scriptsCount: 'сценариев готово',
  noScripts: 'Пока нет сценариев',
  createBelow: 'Создайте новый сценарий ниже',
  newScript: 'Новый сценарий',
  importText: 'Импортировать',
  deleteScriptMsg: 'Удалить сценарий?',
  cannotUndo: 'Это действие нельзя отменить.',
  cancel: 'Отмена',
  delete: 'Удалить',
  myVideos: 'Мои записи',
  saved: 'Сохранено!',
  save: 'Сохранить',
  menu: 'Меню',
  ready: 'ГОТОВО',
  recording: 'ЗАПИСЬ',
  reading: 'ЧТЕНИЕ',
  read: 'ЧИТАТЬ',
  flipCamera: 'Переключить камеру',
  getReady: 'Приготовьтесь...',
  videoSettings: 'Настройки видео',
  textColor: 'Цвет текста',
  quality: 'Качество',
  webmNote: '✓ Все видео сохраняются в формате WebM.',
  eyeContact: 'Режим зрительного контакта (Ширина)',
  countdown: 'Обратный отсчёт',
  saving: 'Сохранение...',
  saveSuccess: 'Сохранено на устройстве!',
  saveError: 'Ошибка при сохранении!',
  saveToDevice: 'Сохранить на устройство',
  deleteAndRetake: 'Удалить и повторить',
  newRecording: 'Новая запись',
  sortNewest: 'Сортировка: Сначала новые',
  noVideos: 'Пока нет видео',
  recordFirst: 'Запишите первое видео с экрана записи.',
  videoLoading: 'Загрузка видео...',
  switchToLang: 'Türkçe\'ye Geç',
  deleteVideoMsg: 'Удалить это видео?',
  deleteError: 'Ошибка удаления: ',
  shareError: 'Ошибка публикации: ',
  shareVideoTitle: 'Поделиться видео',
  recordedWith: 'Записано с ScriptFlow',
  noVideosDesc: 'Сохранённые видео не найдены.',
  recordingPrefix: 'Запись ',
  playVideo: 'Воспроизвести видео',
  share: 'Поделиться',
  tutorial: 'Как использовать',
  tutorialStep1Title: 'Добавить сценарий',
  tutorialStep1Desc: 'На экране «Мои сценарии» нажмите «Новый сценарий» чтобы написать или импортировать текст.',
  tutorialStep2Title: 'Редактировать',
  tutorialStep2Desc: 'Используйте кнопки A- и A+ для настройки размера текста.',
  tutorialStep3Title: 'Запись и суфлёр',
  tutorialStep3Desc: 'Перейдите на экран записи. Выберите камеру и настройте скорость прокрутки.',
  tutorialStep4Title: 'Поделиться',
  tutorialStep4Desc: 'После записи сохраните видео и поделитесь им в социальных сетях.',
  tutorialStep5Title: 'Bluetooth-пульт',
  tutorialStep5Desc: 'Подключите Bluetooth-презентер для дистанционного управления суфлёром.',
  tutorialBack: 'Назад',
  tutorialNext: 'Далее',
  tutorialFinish: 'Начать',
  splashTagline: 'Умный суфлёр для профессиональных съёмок',
  splashLoading: 'Загрузка...',
  langSwitch: 'Türkçe\'ye Geç',
  videoRecord: 'Записать видео',
  audioRecord: 'Записать аудио',
  loading: 'Загрузка...',
  scriptsReady: 'сценариев готово',
  wordCountUpper: 'СЛОВ',
  bgColor: 'Цвет фона',
  camSettings: 'Настройки камеры (Pro)',
  fps: 'Частота кадров (FPS)',
  zoom: 'Масштаб',
  smartVoice: 'Умный голос',
  camBottom: 'Половина экрана',
  fullScreen: 'Полный экран',
  cleanText: 'Чистый текст',
  color_none: 'Прозрачный',
  color_black: 'Чёрный',
  color_navy: 'Тёмно-синий',
  color_dark: 'Тёмно-серый',
  color_green: 'Зелёный',
  color_red: 'Красный',
  color_purple: 'Фиолетовый',
  color_white: 'Белый',
  filter_clean: 'Чистый',
  filter_warm: 'Тёплый',
  filter_cool: 'Холодный',
  filter_cinema: 'Кино',
  filter_portrait: 'Портрет',
  filter_studio: 'Студия',
  filter_bw: 'Ч/Б',
  filter_vivid: 'Яркий',
  filter_beauty: 'Красота', filter_retro: 'Ретро', filter_dramatic: 'Драматичный', filter_golden: 'Золотой час', filter_broadcast: 'Эфир', filter_matte: 'Матовый', filter_night: 'Ночь',
  width_wide: 'Широкий',
  width_medium: 'Средний',
  width_narrow: 'Узкий',
};

// ── PORTUGUÊS (Brasil) ───────────────────────────────────────────────────
const ptTranslations = {
  appName: 'ScriptFlow', myScripts: 'Meus Roteiros', createNew: 'Criar novo roteiro',
  importTxt: 'Importar arquivo .TXT', scripts: 'Roteiros', editor: 'Editor',
  record: 'Gravar', settings: 'Configurações', filter: 'Filtro', favorites: 'Favoritos',
  recentRecordings: 'Últimas gravações', cloudSync: 'Sincronização em nuvem',
  helpSupport: 'Ajuda e suporte', editScript: 'Editar roteiro',
  startRecording: 'Iniciar gravação', titlePlaceholder: 'Título do roteiro',
  contentPlaceholder: 'Comece a digitar seu roteiro...', wordCount: 'palavras',
  start: 'Iniciar', stop: 'Parar', startRec: 'Iniciar gravação', size: 'Tamanho',
  viewMode: 'Layout', prompterOnly: 'Só texto', filters: 'Filtros', layouts: 'Layouts',
  textSize: 'Tamanho do texto', close: 'Fechar', reviewRecording: 'Revisar gravação',
  discardRetake: 'Descartar e regravar', saveVideo: 'Salvar vídeo',
  cameraFilters: 'Filtros de câmera', language: 'Idioma',
  untitledScript: 'Roteiro sem título', goodMorning: 'Bom dia',
  goodAfternoon: 'Boa tarde', goodEvening: 'Boa noite',
  scriptsCount: 'roteiros · pronto', noScripts: 'Nenhum roteiro ainda',
  createBelow: 'Crie um novo roteiro abaixo', newScript: 'Novo roteiro',
  importText: 'Importar', deleteScriptMsg: 'Excluir roteiro?',
  cannotUndo: 'Esta ação não pode ser desfeita.', cancel: 'Cancelar', delete: 'Excluir',
  myVideos: 'Meus vídeos', saved: 'Salvo!', save: 'Salvar', menu: 'Menu',
  ready: 'PRONTO', recording: 'GRAVANDO', reading: 'LENDO', read: 'LER',
  flipCamera: 'Virar câmera', getReady: 'Prepare-se...', videoSettings: 'Configurações de vídeo',
  textColor: 'Cor do texto', quality: 'Qualidade',
  webmNote: '✓ Todos os vídeos são salvos em formato WebM.',
  eyeContact: 'Modo contato visual (Largura)', countdown: 'Contagem regressiva',
  saving: 'Salvando...', saveSuccess: 'Salvo no seu dispositivo!',
  saveError: 'Erro ao salvar!', saveToDevice: 'Salvar no dispositivo',
  deleteAndRetake: 'Excluir e regravar', newRecording: 'Nova gravação',
  sortNewest: 'Ordenar: Mais recente', noVideos: 'Nenhum vídeo ainda',
  recordFirst: 'Grave seu primeiro vídeo na tela de gravação.',
  videoLoading: 'Carregando vídeo...', switchToLang: 'Türkçe\'ye Geç',
  deleteVideoMsg: 'Excluir este vídeo?', deleteError: 'Erro ao excluir: ',
  shareError: 'Erro ao compartilhar: ', shareVideoTitle: 'Compartilhar vídeo',
  recordedWith: 'Gravado com ScriptFlow', noVideosDesc: 'Nenhum vídeo salvo encontrado.',
  recordingPrefix: 'Gravação ', playVideo: 'Reproduzir vídeo', share: 'Compartilhar',
  tutorial: 'Como usar', tutorialStep1Title: 'Adicionar roteiro',
  tutorialStep1Desc: 'Na tela Meus Roteiros, toque em "Novo roteiro" para escrever ou importar um arquivo.',
  tutorialStep2Title: 'Editar', tutorialStep2Desc: 'Use os botões A- e A+ para ajustar o tamanho do texto.',
  tutorialStep3Title: 'Gravar e Prompter',
  tutorialStep3Desc: 'Vá para a tela de gravação. Escolha a câmera e ajuste a velocidade de rolagem.',
  tutorialStep4Title: 'Compartilhar',
  tutorialStep4Desc: 'Após gravar, salve o vídeo e compartilhe nas redes sociais.',
  tutorialStep5Title: 'Controle Bluetooth',
  tutorialStep5Desc: 'Conecte um apresentador Bluetooth para controlar o prompter remotamente.',
  tutorialBack: 'Voltar', tutorialNext: 'Próximo', tutorialFinish: 'Começar',
  splashTagline: 'Prompter inteligente para gravações profissionais',
  splashLoading: 'Carregando...', langSwitch: 'Türkçe\'ye Geç',
  videoRecord: 'Gravar vídeo', audioRecord: 'Gravar áudio', loading: 'Carregando...',
  scriptsReady: 'roteiros prontos', wordCountUpper: 'PALAVRAS',
  bgColor: 'Cor de fundo', camSettings: 'Configurações de câmera (Pro)',
  fps: 'Taxa de quadros (FPS)', zoom: 'Zoom', smartVoice: 'Voz inteligente',
  camBottom: 'Câmera embaixo', fullScreen: 'Tela cheia',
  color_none: 'Transparente', color_black: 'Preto', color_navy: 'Azul-marinho',
  color_dark: 'Cinza escuro', color_green: 'Verde', color_red: 'Vermelho',
  color_purple: 'Roxo', color_white: 'Branco',
  filter_clean: 'Limpo', filter_warm: 'Quente', filter_cool: 'Frio',
  filter_cinema: 'Cinema', filter_portrait: 'Retrato', filter_studio: 'Estúdio',
  filter_bw: 'P&B', filter_vivid: 'Vivo', filter_beauty: 'Beleza', filter_retro: 'Retro', filter_dramatic: 'Dramático', filter_golden: 'Hora Dourada', filter_broadcast: 'Transmissão', filter_matte: 'Mate', filter_night: 'Noite',
  width_wide: 'Largo', width_medium: 'Médio', width_narrow: 'Estreito',
};

// ── ITALIANO ──────────────────────────────────────────────────────────────
const itTranslations = {
  appName: 'ScriptFlow', myScripts: 'I miei copioni', createNew: 'Crea nuovo copione',
  importTxt: 'Importa file .TXT', scripts: 'Copioni', editor: 'Editor',
  record: 'Registra', settings: 'Impostazioni', filter: 'Filtro', favorites: 'Preferiti',
  recentRecordings: 'Registrazioni recenti', cloudSync: 'Sincronizzazione cloud',
  helpSupport: 'Aiuto e supporto', editScript: 'Modifica copione',
  startRecording: 'Avvia registrazione', titlePlaceholder: 'Titolo del copione',
  contentPlaceholder: 'Inizia a scrivere il tuo copione...', wordCount: 'parole',
  start: 'Avvia', stop: 'Ferma', startRec: 'Avvia registrazione', size: 'Dimensione',
  viewMode: 'Layout', prompterOnly: 'Solo testo', filters: 'Filtri', layouts: 'Layout',
  textSize: 'Dimensione testo', close: 'Chiudi', reviewRecording: 'Rivedi registrazione',
  discardRetake: 'Elimina e riprendi', saveVideo: 'Salva video',
  cameraFilters: 'Filtri fotocamera', language: 'Lingua',
  untitledScript: 'Copione senza titolo', goodMorning: 'Buongiorno',
  goodAfternoon: 'Buon pomeriggio', goodEvening: 'Buonasera',
  scriptsCount: 'copioni · pronti', noScripts: 'Nessun copione ancora',
  createBelow: 'Crea un nuovo copione qui sotto', newScript: 'Nuovo copione',
  importText: 'Importa', deleteScriptMsg: 'Eliminare il copione?',
  cannotUndo: 'Questa azione non può essere annullata.', cancel: 'Annulla',
  delete: 'Elimina', myVideos: 'I miei video', saved: 'Salvato!', save: 'Salva',
  menu: 'Menu', ready: 'PRONTO', recording: 'REGISTRAZIONE', reading: 'LETTURA',
  read: 'LEGGI', flipCamera: 'Cambia fotocamera', getReady: 'Preparati...',
  videoSettings: 'Impostazioni video', textColor: 'Colore testo', quality: 'Qualità',
  webmNote: '✓ Tutti i video vengono salvati in formato WebM.',
  eyeContact: 'Modalità contatto visivo (Larghezza)', countdown: 'Conto alla rovescia',
  saving: 'Salvataggio...', saveSuccess: 'Salvato sul dispositivo!',
  saveError: 'Errore nel salvataggio!', saveToDevice: 'Salva sul dispositivo',
  deleteAndRetake: 'Elimina e riprendi', newRecording: 'Nuova registrazione',
  sortNewest: 'Ordina: Più recente', noVideos: 'Nessun video ancora',
  recordFirst: 'Registra il tuo primo video dalla schermata di registrazione.',
  videoLoading: 'Caricamento video...', switchToLang: 'Türkçe\'ye Geç',
  deleteVideoMsg: 'Eliminare questo video?', deleteError: 'Errore eliminazione: ',
  shareError: 'Errore condivisione: ', shareVideoTitle: 'Condividi video',
  recordedWith: 'Registrato con ScriptFlow', noVideosDesc: 'Nessun video salvato trovato.',
  recordingPrefix: 'Registrazione ', playVideo: 'Riproduci video', share: 'Condividi',
  tutorial: 'Come usare', tutorialStep1Title: 'Aggiungi copione',
  tutorialStep1Desc: 'Nella schermata I miei copioni, tocca "Nuovo copione" per scrivere o importare un file.',
  tutorialStep2Title: 'Modifica', tutorialStep2Desc: 'Usa i pulsanti A- e A+ per regolare la dimensione del testo.',
  tutorialStep3Title: 'Registra e Prompter',
  tutorialStep3Desc: 'Vai alla schermata di registrazione. Scegli la fotocamera e regola la velocità di scorrimento.',
  tutorialStep4Title: 'Condividi',
  tutorialStep4Desc: 'Dopo la registrazione, salva il video e condividilo sui social media.',
  tutorialStep5Title: 'Telecomando Bluetooth',
  tutorialStep5Desc: 'Collega un presentatore Bluetooth per controllare il prompter da remoto.',
  tutorialBack: 'Indietro', tutorialNext: 'Avanti', tutorialFinish: 'Inizia',
  splashTagline: 'Prompter intelligente per riprese professionali',
  splashLoading: 'Caricamento...', langSwitch: 'Türkçe\'ye Geç',
  videoRecord: 'Registra video', audioRecord: 'Registra audio', loading: 'Caricamento...',
  scriptsReady: 'copioni pronti', wordCountUpper: 'PAROLE',
  bgColor: 'Colore sfondo', camSettings: 'Impostazioni fotocamera (Pro)',
  fps: 'Frequenza fotogrammi (FPS)', zoom: 'Zoom', smartVoice: 'Voce intelligente',
  camBottom: 'Fotocamera in basso', fullScreen: 'Schermo intero',
  color_none: 'Trasparente', color_black: 'Nero', color_navy: 'Blu marino',
  color_dark: 'Grigio scuro', color_green: 'Verde', color_red: 'Rosso',
  color_purple: 'Viola', color_white: 'Bianco',
  filter_clean: 'Pulito', filter_warm: 'Caldo', filter_cool: 'Freddo',
  filter_cinema: 'Cinema', filter_portrait: 'Ritratto', filter_studio: 'Studio',
  filter_bw: 'B/N', filter_vivid: 'Vivido', filter_beauty: 'Bellezza', filter_retro: 'Retro', filter_dramatic: 'Drammatico', filter_golden: "Ora d'Oro", filter_broadcast: 'Trasmissione', filter_matte: 'Opaco', filter_night: 'Notte',
  width_wide: 'Largo', width_medium: 'Medio', width_narrow: 'Stretto',
};

const koTranslations = {
  appName:'ScriptFlow', myScripts:'나의 스크립트', createNew:'새 스크립트 만들기',
  importTxt:'.TXT 파일 가져오기', scripts:'스크립트', editor:'편집기',
  record:'녹화', settings:'설정', filter:'필터', favorites:'즐겨찾기',
  recentRecordings:'최근 녹화', cloudSync:'클라우드 동기화',
  helpSupport:'도움말 및 지원', editScript:'스크립트 편집',
  startRecording:'녹화 시작', titlePlaceholder:'스크립트 제목',
  contentPlaceholder:'스크립트를 입력하세요...', wordCount:'단어',
  start:'시작', stop:'정지', startRec:'녹화 시작', size:'크기',
  viewMode:'레이아웃', prompterOnly:'텍스트만', filters:'필터', layouts:'레이아웃',
  textSize:'글자 크기', close:'닫기', reviewRecording:'녹화 확인',
  discardRetake:'삭제 후 재촬영', saveVideo:'동영상 저장',
  cameraFilters:'카메라 필터', language:'언어',
  untitledScript:'제목 없는 스크립트', goodMorning:'안녕하세요',
  goodAfternoon:'안녕하세요', goodEvening:'안녕하세요',
  scriptsCount:'스크립트 준비됨', noScripts:'스크립트가 없습니다',
  createBelow:'아래에서 새 스크립트를 만드세요', newScript:'새 스크립트',
  importText:'가져오기', deleteScriptMsg:'스크립트를 삭제할까요?',
  cannotUndo:'이 작업은 되돌릴 수 없습니다.', cancel:'취소', delete:'삭제',
  myVideos:'나의 동영상', saved:'저장되었습니다!', save:'저장', menu:'메뉴',
  ready:'준비', recording:'녹화 중', reading:'읽기 중', read:'읽기',
  flipCamera:'카메라 전환', getReady:'준비하세요...',
  videoSettings:'동영상 설정', textColor:'텍스트 색상', quality:'화질',
  webmNote:'✓ 모든 동영상은 WebM 형식으로 저장됩니다.',
  eyeContact:'시선 접촉 모드 (너비)', countdown:'카운트다운',
  saving:'저장 중...', saveSuccess:'기기에 저장되었습니다!',
  saveError:'저장 오류!', saveToDevice:'기기에 저장',
  deleteAndRetake:'삭제 후 재촬영', newRecording:'새 녹화',
  sortNewest:'정렬: 최신순', noVideos:'동영상이 없습니다',
  recordFirst:'녹화 화면에서 첫 동영상을 찍으세요.',
  videoLoading:'동영상 로딩 중...', switchToLang:'Türkçeye Geç',
  deleteVideoMsg:'이 동영상을 삭제하시겠습니까?',
  deleteError:'삭제 오류: ', shareError:'공유 오류: ',
  shareVideoTitle:'동영상 공유', recordedWith:'ScriptFlow로 녹화됨',
  noVideosDesc:'저장된 동영상이 없습니다.', recordingPrefix:'녹화 ',
  playVideo:'동영상 재생', share:'공유',
  tutorial:'사용 방법', tutorialStep1Title:'스크립트 추가',
  tutorialStep1Desc:'나의 스크립트 화면에서 "새 스크립트"를 눌러 텍스트를 작성하거나 파일을 가져오세요.',
  tutorialStep2Title:'편집', tutorialStep2Desc:'A- 및 A+ 버튼으로 글자 크기를 조정하세요.',
  tutorialStep3Title:'녹화 및 프롬프터',
  tutorialStep3Desc:'녹화 화면으로 이동하여 카메라를 선택하고 스크롤 속도를 조정하세요.',
  tutorialStep4Title:'공유', tutorialStep4Desc:'녹화 후 동영상을 저장하고 SNS에 공유하세요.',
  tutorialStep5Title:'블루투스 리모컨',
  tutorialStep5Desc:'블루투스 프레젠터를 연결하여 프롬프터를 원격 조종하세요.',
  tutorialBack:'이전', tutorialNext:'다음', tutorialFinish:'시작',
  splashTagline:'전문 촬영을 위한 스마트 프롬프터',
  splashLoading:'로딩 중...', langSwitch:'Türkçeye Geç',
  videoRecord:'동영상 녹화', audioRecord:'오디오 녹화', loading:'로딩 중...',
  scriptsReady:'스크립트 준비됨', wordCountUpper:'단어',
  bgColor:'배경색', camSettings:'카메라 설정 (Pro)',
  fps:'프레임 속도 (FPS)', zoom:'확대', smartVoice:'스마트 보이스',
  camBottom:'카메라 하단', fullScreen:'전체 화면',
  color_none:'투명', color_black:'검정', color_navy:'네이비', color_dark:'진회색',
  color_green:'녹색', color_red:'빨간색', color_purple:'보라색', color_white:'흰색',
  filter_clean:'클린', filter_warm:'따뜻한', filter_cool:'시원한',
  filter_cinema:'시네마', filter_portrait:'인물', filter_studio:'스튜디오',
  filter_bw:'흑백', filter_vivid:'선명한', filter_beauty: '뷰티', filter_retro: '레트로', filter_dramatic: '드라마틱', filter_golden: '골든 아워', filter_broadcast: '방송', filter_matte: '매트', filter_night: '밤',
  width_wide:'넓게', width_medium:'중간', width_narrow:'좁게',
};

const azTranslations = {
  appName:'ScriptFlow', myScripts:'Mənim Skriptlərim', createNew:'Yeni skript yarat',
  importTxt:'.TXT fayl idxal et', scripts:'Skriptlər', editor:'Redaktor',
  record:'Qeyd', settings:'Parametrlər', filter:'Filtr', favorites:'Sevimlilər',
  recentRecordings:'Son qeydlər', cloudSync:'Bulud sinxronizasiyası',
  helpSupport:'Kömək və dəstək', editScript:'Skripti redaktə et',
  startRecording:'Qeydi başlat', titlePlaceholder:'Skript başlığı',
  contentPlaceholder:'Skriptinizi buraya yazmağa başlayın...', wordCount:'söz',
  start:'Başlat', stop:'Dayandır', startRec:'Qeydi başlat', size:'Ölçü',
  viewMode:'Düzən', prompterOnly:'Yalnız mətn', filters:'Filtrlər', layouts:'Düzənlər',
  textSize:'Mətn ölçüsü', close:'Bağla', reviewRecording:'Qeydi nəzərdən keçir',
  discardRetake:'Sil və yenidən çək', saveVideo:'Videoyu saxla',
  cameraFilters:'Kamera filtrlər', language:'Dil',
  untitledScript:'Başlıqsız skript', goodMorning:'Səhəriniz xeyir',
  goodAfternoon:'Günortanız xeyir', goodEvening:'Axşamınız xeyir',
  scriptsCount:'skript hazırdır', noScripts:'Hələlik skript yoxdur',
  createBelow:'Aşağıda yeni skript yaradın', newScript:'Yeni skript',
  importText:'İdxal et', deleteScriptMsg:'Skripti silmək istəyirsinizmi?',
  cannotUndo:'Bu əməliyyatı geri qaytarmaq mümkün deyil.', cancel:'Ləğv et', delete:'Sil',
  myVideos:'Mənim Videolarım', saved:'Saxlanıldı!', save:'Saxla', menu:'Menyu',
  ready:'HAZIR', recording:'QEYDİYYAT', reading:'OXUNUR', read:'OXU',
  flipCamera:'Kameranı döndür', getReady:'Hazırlaşın...',
  videoSettings:'Video parametrləri', textColor:'Mətn rəngi', quality:'Keyfiyyət',
  webmNote:'✓ Bütün videolar WebM formatında saxlanılır.',
  eyeContact:'Göz təması rejimi (Genişlik)', countdown:'Geri sayım',
  saving:'Saxlanılır...', saveSuccess:'Cihazda saxlanıldı!',
  saveError:'Saxlama xətası!', saveToDevice:'Cihazda saxla',
  deleteAndRetake:'Sil və yenidən çək', newRecording:'Yeni qeyd',
  sortNewest:'Sırala: Ən yeni', noVideos:'Hələlik video yoxdur',
  recordFirst:'Qeyd ekranından ilk videonu çəkin.',
  videoLoading:'Video yüklənir...', switchToLang:'Türkçeye Geç',
  deleteVideoMsg:'Bu videonu silmək istəyirsinizmi?',
  deleteError:'Silmə xətası: ', shareError:'Paylaşma xətası: ',
  shareVideoTitle:'Videoyu paylaş', recordedWith:'ScriptFlow ilə çəkildi',
  noVideosDesc:'Saxlanılmış video tapılmadı.', recordingPrefix:'Qeyd ',
  playVideo:'Videoyu oynat', share:'Paylaş',
  tutorial:'Necə istifadə etməli', tutorialStep1Title:'Skript əlavə et',
  tutorialStep1Desc:'Mənim Skriptlərim ekranında "Yeni skript"ə toxunaraq mətni yazın.',
  tutorialStep2Title:'Redaktə et', tutorialStep2Desc:'Mətn ölçüsünü tənzimləmək üçün A- və A+ düymələrindən istifadə edin.',
  tutorialStep3Title:'Qeyd və Prompter',
  tutorialStep3Desc:'Qeyd ekranına keçin. Kameranı seçin və sürüşdürmə sürətini tənzimləyin.',
  tutorialStep4Title:'Paylaş', tutorialStep4Desc:'Qeydin ardından videoyu saxlayın və sosial mediada paylaşın.',
  tutorialStep5Title:'Bluetooth pult',
  tutorialStep5Desc:'Prompteri uzaqdan idarə etmək üçün Bluetooth təqdimatçı qoşun.',
  tutorialBack:'Geri', tutorialNext:'İrəli', tutorialFinish:'Başlat',
  splashTagline:'Peşəkar çəkilişlər üçün ağıllı prompter',
  splashLoading:'Yüklənir...', langSwitch:'Türkçeye Geç',
  videoRecord:'Video çək', audioRecord:'Səs çək', loading:'Yüklənir...',
  scriptsReady:'skript hazırdır', wordCountUpper:'SÖZ',
  bgColor:'Arxa plan rəngi', camSettings:'Kamera parametrləri (Pro)',
  fps:'Kadr sürəti (FPS)', zoom:'Zum', smartVoice:'Ağıllı səs',
  camBottom:'Kamera aşağıda', fullScreen:'Tam ekran',
  color_none:'Şəffaf', color_black:'Qara', color_navy:'Tünd mavi',
  color_dark:'Tünd boz', color_green:'Yaşıl', color_red:'Qırmızı',
  color_purple:'Bənövşəyi', color_white:'Ağ',
  filter_clean:'Təmiz', filter_warm:'İsti', filter_cool:'Sərin',
  filter_cinema:'Kino', filter_portrait:'Portret', filter_studio:'Studiya',
  filter_bw:'Q/A', filter_vivid:'Canlı', filter_beauty: 'Hamar', filter_retro: 'Retro', filter_dramatic: 'Dramatik', filter_golden: 'Qızıl Saat', filter_broadcast: 'Yayım', filter_matte: 'Mat', filter_night: 'Gecə',
  width_wide:'Geniş', width_medium:'Orta', width_narrow:'Dar',
};

const translations = { tr: trTranslations, en: enTranslations, de: deTranslations, es: esTranslations, fr: frTranslations, ru: ruTranslations, pt: ptTranslations, it: itTranslations, ko: koTranslations, az: azTranslations };

export const LANGUAGES = [
  { code: 'tr', label: 'Türkçe',      flag: '🇹🇷' },
  { code: 'en', label: 'English',     flag: '🇬🇧' },
  { code: 'de', label: 'Deutsch',     flag: '🇩🇪' },
  { code: 'es', label: 'Español',     flag: '🇪🇸' },
  { code: 'fr', label: 'Français',    flag: '🇫🇷' },
  { code: 'ru', label: 'Русский',     flag: '🇷🇺' },
  { code: 'pt', label: 'Português',   flag: '🇧🇷' },
  { code: 'it', label: 'Italiano',    flag: '🇮🇹' },
  { code: 'ko', label: '한국어',       flag: '🇰🇷' },
  { code: 'az', label: 'Azərbaycanca',flag: '🇦🇿' },
];

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(localStorage.getItem('sf_lang') || 'tr');

  const setLanguage = (code) => {
    setLang(code);
    localStorage.setItem('sf_lang', code);
  };

  const t = (key) => translations[lang]?.[key] || translations['en']?.[key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
