import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    appName: 'ScriptFlow',
    myScripts: 'My Scripts',
    createNew: 'Create New Script',
    importTxt: 'Import .TXT File',
    scripts: 'Scripts',
    editor: 'Editor',
    record: 'Record',
    settings: 'Settings',
    filter: 'Filter',
    favorites: 'Favorites',
    recentRecordings: 'Recent Recordings',
    cloudSync: 'Cloud Sync',
    helpSupport: 'Help & Support',
    editScript: 'Edit Script',
    startRecording: 'Start Recording',
    titlePlaceholder: 'Script Title',
    contentPlaceholder: 'Start typing your script here...',
    wordCount: 'words',
    start: 'Start',
    stop: 'Stop',
    startRec: 'Start Recording',
    size: 'Size',
    viewMode: 'Layout',
    prompterOnly: 'Prompter Only',
    filters: 'Filters',
    layouts: 'Layouts',
    textSize: 'Text Size',
    close: 'Close',
    reviewRecording: 'Review Recording',
    discardRetake: 'Discard & Retake',
    saveVideo: 'Save Video',
    cameraFilters: 'Camera Filters',
    language: 'Language',
    untitledScript: 'Untitled Script',
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    scriptsCount: 'scripts · you are ready',
    noScripts: 'No scripts yet',
    createBelow: 'Create a new script below',
    newScript: 'New Script',
    importText: 'Import',
    deleteScriptMsg: 'Delete script?',
    cannotUndo: 'This action cannot be undone.',
    cancel: 'Cancel',
    delete: 'Delete',
    myVideos: 'My Videos',
    saved: 'Saved!',
    save: 'Save',
    menu: 'Menu',
    ready: 'READY',
    recording: 'RECORD',
    reading: 'READING',
    read: 'READ',
    flipCamera: 'Flip Camera',
    getReady: 'Get Ready...',
    videoSettings: 'Video Settings',
    textColor: 'Text Color',
    quality: 'Quality',
    webmNote: '✓ All videos are saved in WebM format for device compatibility.',
    eyeContact: 'Eye Contact Mode (Width)',
    countdown: 'Countdown',
    saving: 'Saving...',
    saveSuccess: 'Saved to your device!',
    saveError: 'Error saving recording!',
    saveToDevice: 'Save to Device',
    deleteAndRetake: 'Delete & Retake',
    newRecording: 'New Recording',
    sortNewest: 'Sort: Newest First',
    noVideos: 'No videos yet',
    recordFirst: 'Record your first video from the record screen.',
    videoLoading: 'Loading video...',
    switchToLang: 'Türkçe\'ye Geç',
    deleteVideoMsg: 'Are you sure you want to delete this video?',
    deleteError: 'Error deleting: ',
    shareError: 'Share error: ',
    shareVideoTitle: 'Share Video',
    recordedWith: 'Recorded with ScriptFlow',
    noVideosDesc: 'No saved videos found.',
    recordingPrefix: 'Recording ',
    playVideo: 'Play Video',
    share: 'Share',
    tutorial: 'How to Use',
    tutorialStep1Title: 'Add a Script',
    tutorialStep1Desc: 'On the My Scripts screen, tap "New Script" to write your text or import an existing file from your device.',
    tutorialStep2Title: 'Edit',
    tutorialStep2Desc: 'While editing, use the A- and A+ buttons at the bottom to adjust the text size to suit your eyes.',
    tutorialStep3Title: 'Record & Prompter',
    tutorialStep3Desc: 'Go to the Record screen. Select front/back camera from the camera icon. Adjust scroll speed with the +/- buttons on the right and start recording.',
    tutorialStep4Title: 'Share',
    tutorialStep4Desc: 'When recording finishes, tap "Save to Device" then share instantly to social media or friends.',
    tutorialStep5Title: 'Bluetooth Remote',
    tutorialStep5Desc: 'Connect any Bluetooth presentation clicker or remote to control the prompter. Use Space/Play to start, and Up/Down arrows to adjust speed remotely.',
    tutorialBack: 'Back',
    tutorialNext: 'Next',
    tutorialFinish: 'Start',
    splashTagline: 'Smart prompter for professional shots',
    splashLoading: 'Loading...',
    langSwitch: 'Switch to Turkish',
  },
  tr: {
    appName: 'ScriptFlow',
    myScripts: 'Metinlerim',
    createNew: 'Yeni Metin Oluştur',
    importTxt: '.TXT Dosyası İçe Aktar',
    scripts: 'Metinler',
    editor: 'Düzenle',
    record: 'Kayıt',
    settings: 'Ayarlar',
    filter: 'Filtre',
    favorites: 'Favoriler',
    recentRecordings: 'Son Kayıtlar',
    cloudSync: 'Bulut Senkron',
    helpSupport: 'Yardım & Destek',
    editScript: 'Metni Düzenle',
    startRecording: 'Kaydı Başlat',
    titlePlaceholder: 'Metin Başlığı',
    contentPlaceholder: 'Metninizi buraya yazmaya başlayın...',
    wordCount: 'kelime',
    start: 'Başlat',
    stop: 'Durdur',
    startRec: 'Kayda Başla',
    size: 'Boyut',
    viewMode: 'Görünüm',
    prompterOnly: 'Sadece Metin',
    filters: 'Filtreler',
    layouts: 'Düzen',
    textSize: 'Yazı Boyutu',
    close: 'Kapat',
    reviewRecording: 'Kaydı İncele',
    discardRetake: 'Sil & Tekrar Çek',
    saveVideo: 'Videoyu Kaydet',
    cameraFilters: 'Kamera Filtreleri',
    language: 'Dil',
    untitledScript: 'İsimsiz Metin',
    goodMorning: 'Günaydın',
    goodAfternoon: 'İyi günler',
    goodEvening: 'İyi akşamlar',
    scriptsCount: 'metin · hepsine hazırsın',
    noScripts: 'Henüz metin yok',
    createBelow: 'Aşağıdan yeni bir metin oluştur',
    newScript: 'Yeni Metin',
    importText: 'İçe Aktar',
    deleteScriptMsg: 'Metni sil?',
    cannotUndo: 'Bu işlem geri alınamaz.',
    cancel: 'İptal',
    delete: 'Sil',
    myVideos: 'Videolarım',
    saved: 'Kaydedildi!',
    save: 'Kaydet',
    menu: 'Menü',
    ready: 'HAZIR',
    recording: 'KAYIT',
    reading: 'OKUNUYOR',
    read: 'OKU',
    flipCamera: 'Kamerayı Çevir',
    getReady: 'Hazırlan...',
    videoSettings: 'Video Ayarları',
    textColor: 'Yazı Rengi',
    quality: 'Kalite',
    webmNote: '✓ Tüm videolar cihaz uyumluluğu için WebM formatında kaydedilir.',
    eyeContact: 'Göz Teması Modu (Genişlik)',
    countdown: 'Geri Sayım',
    saving: 'Kaydediliyor...',
    saveSuccess: 'Videolarım klasörüne eklendi!',
    saveError: 'Kayıt hatası oluştu!',
    saveToDevice: 'Cihaza Kaydet',
    deleteAndRetake: 'Sil ve Yeniden Çek',
    newRecording: 'Yeni Kayda Geç',
    sortNewest: 'Sırala: Yeniden Eskiye',
    noVideos: 'Henüz video yok',
    recordFirst: 'Kayıt ekranından ilk videonuzu çekin.',
    videoLoading: 'Video yükleniyor...',
    switchToLang: 'Switch to English',
    deleteVideoMsg: 'Bu videoyu silmek istediğinize emin misiniz?',
    deleteError: 'Silinirken hata oluştu: ',
    shareError: 'Paylaşım hatası: ',
    shareVideoTitle: 'Videoyu Paylaş',
    recordedWith: 'ScriptFlow ile çekildi',
    noVideosDesc: 'Henüz kayıtlı video bulunmuyor.',
    recordingPrefix: 'Kayıt ',
    playVideo: 'Videoyu oynat',
    share: 'Paylaş',
    tutorial: 'Nasıl Kullanılır?',
    tutorialStep1Title: 'Metin Ekleme',
    tutorialStep1Desc: 'Metinlerim ekranında "Yeni Metin" butonuna basarak okuyacağınız metni yazın veya var olan bir metni cihaza kaydedip uygulamaya aktarın.',
    tutorialStep2Title: 'Düzenleme',
    tutorialStep2Desc: 'Metnini düzenlerken alttaki A- A+ butonlarını kullanarak metnin okuma boyutunu kendi gözünüze uygun hale getirin.',
    tutorialStep3Title: 'Kayıt ve Prompter',
    tutorialStep3Desc: 'Kayıt ekranına geçin. Kamera ikonundan ön/arka kamerayı seçin. Metin akış hızını sağdaki +/- butonlarından ayarlayarak kayda başlayın.',
    tutorialStep4Title: 'Paylaşım',
    tutorialStep4Desc: 'Kayıt bittiğinde "Cihaza Kaydet" diyerek galeriye atabilir, ardından anında sosyal medyada arkadaşlarınızla paylaşabilirsiniz.',
    tutorialStep5Title: 'Bluetooth Kumanda',
    tutorialStep5Desc: 'Telefona bağladığınız herhangi bir Bluetooth sunum kumandası veya deklanşör ile metni uzaktan kontrol edebilirsiniz (Başlat/Durdur ve Hız Ayarı).',
    tutorialBack: 'Geri',
    tutorialNext: 'İleri',
    tutorialFinish: 'Başla',
    splashTagline: 'Profesyonel çekimler için akıllı prompter',
    splashLoading: 'Hazırlanıyor...',
    langSwitch: 'Switch to English',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(localStorage.getItem('sf_lang') || 'tr');

  const toggleLang = () => {
    const newLang = lang === 'tr' ? 'en' : 'tr';
    setLang(newLang);
    localStorage.setItem('sf_lang', newLang);
  };

  const t = (key) => translations[lang][key] || key;

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
